"""Modul Report: membangun dan menyimpan laporan Markdown"""

def letter_grade(score):
    if score >= 85: return 'A'
    if score >= 75: return 'B'
    if score >= 65: return 'C'
    if score >= 50: return 'D'
    return 'E'

def build_markdown_report(records):
    lines = []
    lines.append('# Rekap Nilai Mahasiswa')
    lines.append('')
    lines.append('| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |')
    lines.append('|---|---|---:|---:|:---:|')
    for r in records:
        lines.append(f"| {r['nim']} | {r['nama']} | {r['hadir']:.2f} | {r['nilai_akhir']:.2f} | {r['predikat']} |")
    lines.append('')
    lines.append('Generated by student_performance_tracker')
    return '\n'.join(lines)

def save_text(path, content):
    from pathlib import Path
    Path(path).write_text(content, encoding='utf-8')
